AMBR_BASE_URL = 'https://gi.yatta.top'
AMBR_EVENT_URL = AMBR_BASE_URL + '/assets/data/event.json'
AMBR_CHAR_URL = AMBR_BASE_URL + '/v2/chs/avatar/{}?vh=32F2'
AMBR_WEAPON_URL = AMBR_BASE_URL + '/v2/CHS/weapon/{}?vh=32F6'
AMBR_BOOK_URL = AMBR_BASE_URL + '/v2/chs/book?vh=34F5'
AMBR_BOOK_DETAILS_URL = AMBR_BASE_URL + '/v2/CHS/book/{}?vh=34F5'
AMBR_BOOK_DATA_URL = AMBR_BASE_URL + '/v2/CHS/readable/Book{}?vh=34F5'
AMBR_MONSTER_URL = AMBR_BASE_URL + '/v2/chs/monster/{}?vh=37F4'
AMBR_GCG_LIST_URL = AMBR_BASE_URL + '/v2/chs/gcg?vh=37F4'
AMBR_GCG_DETAIL = AMBR_BASE_URL + '/v2/chs/gcg/{}?vh=37F4'
AMBR_MONSTER_LIST = AMBR_BASE_URL + '/v2/chs/monster?vh=37F4'
AMBR_ICON_URL = AMBR_BASE_URL + '/assets/UI'
AMBR_MONSTER_ICON_URL = f'{AMBR_ICON_URL}/monster/'
AMBR_DAILY_URL = AMBR_BASE_URL + '/v2/chs/dailyDungeon?vh=37F4'
AMBR_UPGRADE_URL = AMBR_BASE_URL + '/v2/chs/upgrade?vh=40F3'
